MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE : 1
  TRANS_USE : 1
  RES_MODE : 1
  HTM_LAYER : 2
  MIX_DIM : 768
  PRETRAIN_PATH_R : '/home/u/catkin_ws/src/reid_ros_pkg/resnet50-19c8e357.pth'
  PRETRAIN_PATH_T : '/home/u/catkin_ws/src/reid_ros_pkg/deit_base_distilled_patch16_224-df68dfff.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('msmt17')
  ROOT_DIR: '/home/u/catkin_ws/src/reid_ros_pkg/'

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  FEAT: 0
OUTPUT_DIR: './real_time_ReID'

