MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  RES_USE : 1
  TRANS_USE : 0
  RES_MODE : 1
  # PRETRAIN_PATH_R : 'your resnet50 pretrain model path'
  PRETRAIN_PATH_R : 'E:\ZHC\FusionReID\FusionReID_Pretrained\resnet50-19c8e357.pth'



INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('msmt17')
  # ROOT_DIR: './data'
  ROOT_DIR: 'E:\ZHC\FusionReID\MSMT17_V1'

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './res_only_20251203'

